import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLbl100kFollowers: String = "100K\nFollowers"
    static let kLblSkills: String = "Skills"
    static let kMsgHiltiStandsFo: String =
        "Hilti stands for quality, innovation, and direct customer relationships. Some 32,000 employees around the world, in more than 120 countries."
    static let kLbl703: String = "703\n"
    static let kLblOffer: String = "OFFER"
    static let kMsgMdUsnavyAs: String = "#MD #USNavy #Astronaut"
    static let kLblUpload: String = "Upload"
    static let kMsgFreshGraduate2: String = "Fresh Graduate - IT Business Analyst"
    static let kLbl182Saves: String = "182\nSaves"
    static let kLbl245Followers: String = "245\nFollowers"
    static let kMsgFreshGraduate3: String = "Fresh Graduate - IT Support"
    static let kLbl2: String = "#"
    static let kMsgDigitalpenang: String = "@DigitalPenang · 1-28"
    static let kLbl1200: String = "12:00"
    static let kMsgFreshGraduate: String = "Fresh Graduate - Software Engineer"
    static let kLblCandidates: String = "Candidates"
    static let kLblWebsite: String = "Website"
    static let kLblJaye2: String = "Jaye"
    static let kLbl100k2: String = "100K\n"
    static let kMsgInternEngine2: String = "#intern #engineering(EE) #operations"
    static let kLbl88k: String = "88K"
    static let kLblSaves: String = "Saves"
    static let kMsgPeriodFe: String = "Period     : Feb2023 - Present"
    static let kMsgCandidatesWho2: String =
        "Candidates who prefer to travel may be given opportunities to travel; Candidates who prefer not to travel may work locally.\nIf candidate’s preference is to travel, all accommodation, allowances, per diems etc. will be fully covered with full benefits provided by the Company.\nOpportunity to work with customers from Malaysia, London, Holland, Paris, United States, Singapore, HK, Japan, Dubai etc."
    static let kMsgCandidatesWith2: String =
        "Candidates with good command of English (spoken and written) as well as communication / convincing skills\nCandidate’s ability and willingness to learn new things - Strong ability to pickup new technical topics quickly and apply them to assignments\nCandidates experience Conceptional and analytical skills with hands-on software development experience (e.g Java, APEX, C# or equivalent)"
    static let kLbl8882: String = "888\n"
    static let kMsgCandidatesProv: String =
        "Candidates proven hands-on experience with Javascript (preferably popular frameworks like AngularJS, React, KnockoutJS etc.), HTML5 & CSS."
    static let kMsgCandidateMust: String =
        "Candidate must be currently undergoing a course in IT / Computer Science / Computer engineering."
    static let kMsgSeniorStartup: String = "Senior Startup Ecosystem Executive"
    static let kMsgCandidatesWith3: String =
        "Candidates with good written and spoken English and Bahasa Malaysia. Written Mandarin, Tamil and other languages is a plus.\nCandidate experience in event planning and management.\nCandidates ready to be based in Penang (not negotiable)."
    static let kMsgAbilityToPerf: String =
        "Ability to perform planning and execution of startup programs in many areas. Comfortable to engage with stakeholders of the ecosystem"
    static let kMsgABachelorSDe: String =
        "A Bachelor’s Degree in Information Technology, Computer Science or equivalent education. (CGPA > 3.5)"
    static let kLblJaye128: String = "@jaye · 1-28"
    static let kLbl58kFollowers: String = "58K\nFollowers"
    static let kMsgJonnyKim1: String = "@Jonny Kim · 1-28"
    static let kLbl58k2: String = "58K"
    static let kLbl10kFollowing: String = "10K\nFollowing"
    static let kMsgCandidatesWho: String =
        "Candidates who prefer to travel may be given opportunities to travel; Candidates who prefer not to travel may work locally."
    static let kLblFlash: String = "Flash"
    static let kMsgPreviousExperi: String =
        "Previous experience in similar role in any government or private startup ecosystem development company is a plus.\nDemonstrate interest and experience in the tech startup space.\nProfessional with good communication skills. Able to articulate yourself clearly.\nRespectful and have good interpersonal skills with people.\nLearn quickly, adapt fast with good self-discipline and organization capabilities."
    static let kMsgPeriod203: String = "Period     : 2016 - 2017"
    static let kMsgCandidatesAble: String =
        "Candidates able to work well in a team, as well as individually.\nCandidates passionate about technology and enjoy software development, riding on the latest technologies."
    static let kLbl99k: String = "99K\n"
    static let kMsgPeriod202: String = "Period     : 2002 - Present"
    static let kLblResume: String = "Resume"
    static let kLbl58kSaves: String = "58K\nSaves"
    static let kLbl100k: String = "100K"
    static let kMsgConstruction: String = "#construction #engineering #software"
    static let kMsgSpecializesA: String = "Specializes : Analytics, Big Data, ML/AI"
    static let kLbl128: String = "1-28"
    static let kLblJonnyKim2: String = "Jonny Kim"
    static let kLblHiring: String = "Hiring"
    static let kMsgFusionexIsAG: String =
        "Fusionex is a global, multi-award winning data technology provider with a strong worldwide presence."
    static let kLbl0Following: String = "0\nFollowing"
    static let kLblHilti: String = "@Hilti"
    static let kMsgInternWebDe: String = "Intern - Web Development"
    static let kMsgDigitalPenang2: String =
        "Digital Penang is a government-linked company owned by the State of Penang to accelerate efforts to capture opportunities in the digital economy"
    static let kLblSamuelCheng: String = "Samuel Cheng"
    static let kMsgInternSoftwa: String = "Intern - Software Engineer"
    static let kLbl245: String = "245\n"
    static let kLbl988Following: String = "988\nFollowing"
    static let kMsgItServices: String = "#IT #services #consulting"
    static let kMsgPeopleAlsoFol: String = "People Also Followed"
    static let kMsgInvolvedInDes: String =
        "Involved in design, coding, testing and deployment of modern information systems. Candidates will have the opportunity to work on state of the art systems running  different programming platform."
    static let kLbl888: String = "888"
    static let kLbl10k: String = "10K\n"
    static let kMsgStatusOngoin: String = "Status : Ongoing (1st Year)    "
    static let kMsgAdvanceDiploma: String =
        "Advance Diploma, Bachelor's Degree, Professional Degree, Master's Degree in IT/ Computer Science/ Computer engineering/ Information System or any IT related fields."
    static let kMsgCompanyJomhac: String = "Company: JomHack"
    static let kLblCompanies: String = "Companies"
    static let kLblCompanyNasa: String = "Company: NASA"
    static let kMsgOurCompanyIs2: String =
        "Our company is work on training International Certificate in Ethical Hacking and other Cybersecurity courses. Also, we can accept Malaysian university students for internship to work as web backend developer or work in marketing section. We cannot pay money (salary) for internship. If you are interested in our courses to register or work as an internship, you can message me for more information. WhatsApp: +60173605097 Montana Education and Training (Malaysia) "
    static let kHttpFail: String = "HTTP request failed"
    static let kLbl88kSaves: String = "88K\nSaves"
    static let kLblYiQing: String = "Yi Qing"
    static let kMsgCurrentlyAStu2: String =
        "Currently a student pursuing Process and Food Engineering in University Putra Malaysia. Continue learning about science, food science, engineering and mechanical things."
    static let kLblFilters: String = "Filters"
    static let kLbl58k: String = "58K\n"
    static let kLblFollowers: String = "Followers"
    static let kMsgCandidateFamil: String =
        "Candidate familiar with stored procedures, SQL, .NET development (Winforms & Web Development).\nCandidates that are familiar with HTML, Javascript etc.\nCandidates experience in OO Programming, 3-tier development and SQL is preferred."
    static let kLblFusionexGroup2: String = "Fusionex Group"
    static let kLblCompanyVhack: String = "Company: Vhack"
    static let kLblJonnyKim: String = "@Jonny Kim"
    static let kMsgDearJayeIM: String =
        "Dear Jaye, I’m reaching out to see if you’d be interested in a Product Intern role. Please let me know if you are available to discuss as we have a position which very much may interest you"
    static let kLblSaved: String = "Saved"
    static let kMsgFusionexgroup: String = "@FusionexGroup · 1-28"
    static let kMsgTertiaryEducat: String =
        "Tertiary education in any field with preference for those with a business, communication or technology degree."
    static let kMsgOurCompanyIs: String =
        "Our company is work on training International Certificate in Ethical Hacking and other Cybersecurity courses. Also, we can accept Malaysian university students for internship to work as web backend developer or work in marketing section. We cannot pay money (salary) for internship. If you are interested in our courses to register or work as an internship, you can message me for more information. WhatsApp: +60173605097 Montana Education and Training (Malaysia) https://www.montana.com.my/"
    static let kLblDigitalPenang2: String = "Digital Penang"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblBenefits: String = "Benefits"
    static let kLblApply: String = "Apply"
    static let kLblFlip: String = "Flip"
    static let kLbl0350: String = "03:50"
    static let kLblPrefer: String = "Prefer"
    static let kLbl108: String = "108\n"
    static let kLbl988: String = "988\n"
    static let kLbl703Followers: String = "703\nFollowers"
    static let kMsgCandidatesWith: String =
        "Candidates with solid hands-on working experience using Microsoft technologies, which consist of the .NET Framework, C# and etc\nCandidate familiar with stored procedures, SQL, .NET development (Winforms & Web Development).\nCandidates experience in OO Programming, 3-tier development and SQL is preferred. Pro-active person with good initiative and good English communication skills."
    static let kMsgInternEngine: String = "#intern #engineering(EE) #engineering(SE)"
    static let kMsgThankYouForP: String = "Thank you for pm me, I will consider about it."
    static let kMsgCompanyUsNav: String = "Company: US Navy"
    static let kLblHilti2: String = "Hilti"
    static let kLblDigitalpenang: String = "@DigitalPenang"
    static let kLblChat: String = "Chat"
    static let kLbl68k: String = "68K\n"
    static let kLblGallery: String = "Gallery"
    static let kLblQualification: String = "Qualification"
    static let kLbl182: String = "182\n"
    static let kLblAboutUs: String = "About Us"
    static let kLbl20k: String = "20K\n"
    static let kLblHilti128: String = "@Hilti · 1-28"
    static let kLblTimer: String = "Timer"
    static let kMsgPeriod20: String = "Period     : 2017 - Present"
    static let kLblFollow: String = "Follow"
    static let kLblLookingFor: String = "Looking for"
    static let kMsgFocusGovernm: String = "Focus : Government Administration"
    static let kLbl100kSaves: String = "100K\nSaves"
    static let kLblSpeed: String = "Speed"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgCurrentlyAStu: String =
        "Currently a student pursuing Computer and Communication System Engineering in University Putra Malaysia. Passionate about technology, science, engineering and investing."
    static let kMsgCandidatesExpe: String =
        "Candidates experience developing mobile applications would be considered an advantage.\nExperience with NodeJS, Swagger, MongoDB, PostgreSQL and MS SQL Server would be considered an advantage.\nPreferably 2-3 years of working experience.\nCandidates who are able to start work immediately will have an added advantage.\nFresh graduates with enthusiasm for learning new skills and technologies are encouraged to apply."
    static let kLblBeauty: String = "Beauty"
    static let kMsgSpecializesS: String = "Specializes : Startup, SME, Entrepreneur"
    static let kLblJaye: String = "@jaye"
    static let kLblJobScope: String = "Job Scope"
    static let kLbl: String = " · "
    static let kMsgStatusOngoin2: String = "Status : Ongoing (2nd Year)    "
    static let kMsgTypeMessage: String = "Type Message ..."
    static let kMsgRole3: String = "Role         : Seal "
    static let kLbl888Saves: String = "888\nSaves"
    static let kMsgRole2: String = "Role         : Astronaut "
    static let kMsgSpecializesE: String =
        "Specializes : Engineering, Power Tools,  \n                        Services, Quality"
    static let kLbl20kFollowers: String = "20K\nFollowers"
    static let kLbl99kFollowers: String = "99K\nFollowers"
    static let kMsgInvolvedInDes2: String =
        "Involved in design, coding, testing and deployment of modern information systems. Candidates will have the opportunity to work on exciting, state of the art systems running on the .NET platform."
    static let kMsgRole5: String = "Role         : Coordinator     "
    static let kMsgRole4: String = "Role         : Medical Doctor"
    static let kLbl0: String = "0\n"
    static let kLbl0Followers: String = "0\nFollowers"
    static let kMsgCourseCompute: String =
        "Course: Computer and Communication  \n               System Engineering"
    static let kMsgCurrentlyAFir: String =
        "Currently a first-year student pursuing Computer and Communication System Engineering in University Putra Malaysia. Continue learning about science, technology, engineering and mathematics"
    static let kMsgFocusItServ: String = "Focus : IT Services and IT Consulting"
    static let kLbl201Following: String = "201\nFollowing"
    static let kLbl88k2: String = "88K\n"
    static let kLbl201: String = "201\n"
    static let kMsgCarryOutTheD: String =
        "Carry out the developer role in a Scrum Team and translate user stories into technical implementation."
    static let kLbl108Saves: String = "108\nSaves"
    static let kLblFusionexgroup: String = "@FusionexGroup"
    static let kMsgHttpsWwwMon: String = "https://www.montana.com.my/"
    static let kMsgCompanyMassac: String =
        "Company: Massachusetts General \n                   Hospital"
    static let kLblFollowing: String = "Following"
    static let kMsgPeriodJu: String = "Period     : Jun 2022 - Present"
    static let kMsgJonathanYongK: String =
        "Jonathan Yong Kim (born 5 February 1984), also called Jonny Kim, is an American US Navy lieutenant commander (and former SEAL), physician, and NASA astronaut."
    static let kLblYog2025: String = "YOG     : 2025"
    static let kLblYog2026: String = "YOG     : 2026"
    static let kMsgDesignAndImpl: String =
        "Design and implement responsive web & mobile applications from front to back using open source frameworks like MEAN, Ionic and Swagger."
    static let kLblEducation: String = "Education"
    static let kMsgFullStackDeve: String = "Full Stack Developer"
    static let kMsgFocusConstru: String = "Focus : Construction "
    static let kMsgRole: String = "Role         : Participant     "
    static let kMsgShowUsWhatYo: String =
        "Show us what you are made of, and we will offer you opportunities to move around the business – to work abroad, experience different job functions and tackle different markets. It is a wonderful way to find the right match for your ambitions and achieve the exciting career you are after."
    static let kLbl68kSaves: String = "68K\nSaves"
    static let kLblExperience: String = "Experience"
}
